# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이상훈, Sanghun Lee
title: Python backend engineer
email: oper6909@gmail.com
website: https://github.com/fregataa

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username:
github_username:  fregataa
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: sanghun-lee-803280222
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  **Python**을 좋아하는 2년차 백엔드 개발자입니다. 서로 배움을 나누고 다같이 성장하기를 즐깁니다. **사용자 경험**과 **개발자 경험**을 개선하는데 성취를 느끼고 기술 부채 줄이기를 좋아합니다.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lablup
        link: https://www.lablup.com/
        # link_text: boringcompany.com
        sub_title: 백엔드 개발자
        caption: 2021.12 - present
        quote: >
            컴퓨팅 자원 분산 관리 플랫폼 제공
        description: | # this will include new lines to allow paragraphs
            * 오픈소스 컨트리뷰톤 아카데미 2022 [Backend.AI 프로젝트 멘토](https://www.oss.kr/contribution_22_projects/show/db0a36a3-a373-4e7b-8cd7-68f4279350e1)
            * Legacy DB 테이블을 2개의 테이블로 분리하고 migration하여 2개의 다른 이슈를 blocking하는 이슈를 해결.
            * SQLAlchemy ORM 도입으로 쉬운 DB 쿼리 및 ORM API 사용 가능.

      - layout: left
        title: 알고리마
        link: https://algorima.io/
        # link_text: boringcompany.com
        sub_title: 풀스택 개발자
        caption: 2020.12 - 2021.12
        quote: >
            AI 교육 웹 플랫폼 제공
        description: | # this will include new lines to allow paragraphs
            * Django, Django rest-framework로 작성된 서버에 API 추가.
            * React, Redux 기반 웹에 polling 기반 사용자 학습 정보 업데이트 추가.
            * Locust.io를 활용하여 load test 코드 작성 및 실시, 백엔드 bottleneck 파악.
            * [GCP Pub/Sub 배포 설정을 수정하여 bottleneck 해결](https://velog.io/@fregataa/GCP-Pubsub-flow-control), AI 훈련 요청 분당 처리량 3개에서 10개로 증가. 
            * 개발환경 Dockerize로 신입 개발자 온보딩 기간 평균 7일에서 3일로 단축.
            * 기능을 수정하거나 추가하기 힘든 백엔드 코드 전반적인 리팩토링.

  - title: Skill # Title for the section
    layout: list
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          <mark>Python, Python asyncio</mark>
          * Python 문법에 익숙합니다. Python asyncio 비동기 코드를 이해하고 작성할 수 있습니다.
          * Type hint를 중요시합니다.
      - layout: left
        description: | # this will include new lines to allow paragraphs
          <mark>SQLalchemy, alembic</mark>
          * SQLAlchemy로 DB schema를 작성하거나 수정하고 쿼리를 문제없이 작성할 수 있습니다.
          * alembic migration 파일을 작성할 수 있습니다.
      - layout: left
        description: | # this will include new lines to allow paragraphs
          <mark>Django, Django rest-framework</mark>
          * Django ORM을 사용할 수 있습니다. Django QuerySet의 laziness 등의 특성을 이해하고 이를 통해 효율적인 쿼리를 작성할 수 있습니다.
      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          <mark>React, Redux</mark>
          * React hook을 활용한 코드를 작성한 경험이 있습니다.
          * Redux를 통해 SPA 상태 관리 코드를 작성한 경험이 있습니다.
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          <mark>PostgreSQL</mark>
          * PostgreSQL 데이터베이스로 구성된 백엔드 서버를 다룬 경험이 있습니다.
      - layout: left
        description: | # this will include new lines to allow paragraphs
          <mark>GCP</mark>
          * GCP GKE에 서비스를 배포한 경험이 있습니다.
          * GCP Pubsub로 메시지를 주고 받는 서비스를 유지보수한 경험이 있습니다.
      - layout: left
        description: | # this will include new lines to allow paragraphs
          <mark>Docker</mark>
          * Web application 개발환경을 dockerize한 경험이 있습니다.
      - layout: left
        title: Collaboration & Other tools
        description: | # this will include new lines to allow paragraphs
          <mark>Git, Github</mark>
          * Git을 통해 협업하는데 익숙합니다.
          * Git과 Github를 통한 크고 작은 오픈소스 기여 경험이 있습니다.

  - title: Other Experience
    layout: list
    content:
      - layout: left
        title: Pycon Korea 2022 세션 발표
        description: |
            SQLAlchemy with asyncio, From Core to ORM
      - layout: left
        title: 오픈소스 컨트리뷰톤 아카데미 2021 Backend.AI 멘티
        description: |
            Backend.AI 프로젝트에 멘티로 참여하여 문서 한글화 참여

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Konkuk University
        caption: 2014 - 2021
        sub_title: BSc Computer Engineering
        description: | # this will include new lines to allow paragraphs
          자료구조, 운영체제, 네트워크 프로그래밍, 소프트웨어 개발방법론 등 전공 수강.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
